Shamelessly copied Zach Holman's bootstrap script
Applause for @holman and https://github.com/holman/dotfiles
Modified bootstrap to be used by Zsh
Appended .symlink to all dot files.
And removed bash files, because I don't use bash anymore.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,37 +1,124 @@
-#!/bin/bash
+#!/bin/zsh
+#
+# bootstrap installs things.
 
-# A "|" separated list of files to exclude from symoblic linking
-exclude="dot|vpm|README.md"
-install_dir=/var/local
-install_log=$install_dir/dot_install.log
+cd "$(dirname "$0")"
+DOTFILES_ROOT=$(pwd)
 
-install() {
-    files=$(ls | egrep -v "\b($exclude)\b")
-    for file in $files; do
-        echo $file | sudo tee -a $install_log > /dev/null
-        ln -vfs $(pwd)/$file ~/.$file
-    done
+set -e
+set +o noclobber
+
+echo ''
+
+info () {
+  printf "  [ \033[00;34m..\033[0m ] $1"
 }
 
-remove() {
-    sudo mkdir -p $install_dir
-    sudo touch $install_log
-    files=$(cat $install_log)
-    for file in $files; do
-        rm -vf ~/.$file
-    done
-    sudo rm $install_log
+user () {
+  printf "\r  [ \033[0;33m?\033[0m ] $1 "
 }
 
-case $1 in
-    "install" )
-        remove
-        install
-        ;;
-    "remove" )
-        remove
-        ;;
-    * )
-        echo "$0 install remove"
-        ;;
-esac
+success () {
+  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+}
+
+fail () {
+  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+  echo ''
+  exit
+}
+
+link_file () {
+  local src=$1 dst=$2
+
+  local overwrite= backup= skip=
+  local action=
+
+  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
+  then
+    if [[ "$overwrite_all" == "false"  &&  "$backup_all" == "false"  &&  "$skip_all" == "false" ]]
+    then
+      local currentSrc="$(readlink $dst)"
+      if [[ "$currentSrc" == "$src" ]]
+      then
+        skip=true;
+      else
+        user "File already exists: $(basename "$src"), what do you want to do? \
+[s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+        read -rs -k 1 action
+
+        case "$action" in
+          o )
+            overwrite=true;;
+          O )
+            overwrite_all=true;;
+          b )
+            backup=true;;
+          B )
+            backup_all=true;;
+          s )
+            skip=true;;
+          S )
+            skip_all=true;;
+          * )
+            ;;
+        esac
+      fi
+    fi
+
+    overwrite=${overwrite:-$overwrite_all}
+    backup=${backup:-$backup_all}
+    skip=${skip:-$skip_all}
+
+    if [[ "$overwrite" == "true" ]]
+    then
+      rm -rf "$dst"
+      success "removed $dst"
+    fi
+
+    if [[ "$backup" == "true" ]]
+    then
+      mv "$dst" "${dst}.backup"
+      success "moved $dst to ${dst}.backup"
+    fi
+
+    if [[ "$skip" == "true" ]]
+    then
+      success "skipped $src"
+    fi
+  fi
+
+  if [[ "$skip" != "true" ]]  # "false" or empty
+  then
+    ln -s "$src" "$dst"
+    success "linked $src to $dst"
+  fi
+}
+
+install_dotfiles () {
+  info 'installing dotfiles'
+
+  local overwrite_all=false backup_all=false skip_all=false
+
+  for src in $(find "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink')
+  do
+    dst="$HOME/.$(basename "${src%.*}")"
+    link_file "$src" "$dst"
+  done
+}
+
+setup_zsh () {
+  # From prezto README on installation
+  setopt EXTENDED_GLOB
+  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N)
+  do
+    ln -vfs "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
+  done
+  chsh -s /bin/zsh
+}
+
+install_dotfiles
+setup_zsh
+
+echo ''
+echo '  All installed!'
